### ISSUE TITLE
how to resize gif image and write to file or buffer

### ISSUE THREAD

**Issue by 2h4dl** [libvips/pyvips#129]
I have a image like below:
 ![img](https://s2.ax1x.com/2019/10/31/KIeVrn.gif)
I want to scale it and write to buffer or file, how to do it?

**Comment by jcupitt** [comment]
Hello @2h4dl, use `thumbnail`, it has extra logic for resizing animated images.

```shell
vips thumbnail brush.gif[n=-1] x.gif 128
```

To make:

![x](https://user-images.githubusercontent.com/580843/67934229-63035980-fbbf-11e9-833c-94ecfe819cb1.gif)

**Comment by 2h4dl** [comment]
Thanks your answer @jcupitt. Still have a question.

I'm trying to read image from internet without knowing its real format, maybe gif image but named a jpg, how to read and scale or crop it? 

I used `pyvips.Image.new_from_buffer` and `pyvips.Image.thumbnail_image` to read a gif, then saved it with `write_to_file`, a still image is given not a animated image.

**Comment by jcupitt** [comment]
Don't use `thumbnail_image` -- it's much slower than `thumbnail`.

You can open an image with `new_from_file` and then check `vips-loader` to get the file type:

```
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> x.get("vips-loader")
'jpegload'
```

**Comment by 2h4dl** [comment]
Hi @jcupitt , it's all right to read an image from local disk with `new_from_file`.
How to read a internet image. Here is my code to read image from interent data.
```
import requests
import pyvips

def image_format(vips_loader):
    vips_loader = vips_loader.split("_")[0]
    if vips_loader == "jpegload":
        return "jpeg"
    elif vips_loader == "pngload":
        return "png"
    elif vips_loader == "gifload":
        return "gif"
    else:
        return "unknown"


image_url = "http://www.example.com/example.jpg"
resp = requests.get(image_url)
try:
    web_image = pyvips.Image.new_from_buffer(resp.content, options="", n=-1) # for gif image
except:
    web_image = pyvips.Image.new_from_buffer(resp.content, options="") # for jpg, png

vips_loader = web_image.get("vips-loader")
image_fmt = image_format(vips_loader)
if image_fmt == "unknown":
    pass
elif image_fmt == "gif":
    # resize op
    scaled_image = pyvips.Image.thumbnail_image(web_image, width=w, height=h)
    # crop op
    # TODO
    #  unknowning how to do it
else:
    # resize op
    scaled_image = pyvips.Image.resize(web_image, scale=0.5)
    # crop
    cropped_image = Image.extract_area(scaled_image , x, y, w, h)
 ``` 

It looks ugly and hard to read.
Any suggestion will be appreciated.

**Comment by jcupitt** [comment]
`new_from_buffer` is very quick -- you can do it just to get the image type.

```python
def loader_from_buffer(buffer):
    image = pyvips.Image.new_from_buffer(buffer)
    return image.get("vips-loader").split("_")[0]

image_url = "http://www.example.com/example.jpg"
buffer = requests.get(image_url).content
loader = loader_from_buffer(buffer)
if loader == "gifload":
    # an animated format -- make a thumbnail of all frame
    thumb = pyvips.Image.thumbnail(buffer, target_width, n=-1)
else:
    thumb = pyvips.Image.thumbnail(buffer, target_width)

# crop: thumbnail has a range of crop options, use one of those if you can

# to do you own crop on animated images, you need to cut the xywh from every frame
# and reassemble as a new animation
```

**Comment by 2h4dl** [comment]
I need to crop specific area, so the manual way is appropriate and  `extract_area` is preferred.
How to get every frame and reassemble as a new animation with pyvips, I still have no idea.

**Comment by jcupitt** [comment]
There's some demo code here:

https://github.com/libvips/libvips/issues/1167#issuecomment-440598247

You'd need to run that after `thumbnail`.

**Comment by zhaohuxing** [comment]
> Hello @2h4dl, use `thumbnail`, it has extra logic for resizing animated images.
> 
> ```python
> thumb = pyvips.Image.thumbnail("brush.gif", 128, n=-1)
> thumb.write_to_file("x.gif")
> ```
> 
> To make:
> 
> ![x](https://user-images.githubusercontent.com/580843/67934229-63035980-fbbf-11e9-833c-94ecfe819cb1.gif)

Current, I use Python 3.8, but throw error 
```
Traceback (most recent call last):
  File "resize_gif.py", line 7, in <module>
    thumb = pyvips.Image.thumbnail("brush.gif", 128, n=-1)
  File "/Users/xzh/.local/share/virtualenvs/vips-image-yHrOgoj2/lib/python3.8/site-packages/pyvips/vimage.py", line 135, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "/Users/xzh/.local/share/virtualenvs/vips-image-yHrOgoj2/lib/python3.8/site-packages/pyvips/voperation.py", line 265, in call
    details = intro.details[name]
KeyError: 'n'
```

**Comment by jcupitt** [comment]
Hello @zhaohuxing,

Your libvips is probably too old. Do you know what version you are using?

**Comment by zhaohuxing** [comment]
> Hello @zhaohuxing,
> 
> Your libvips is probably too old. Do you know what version you are using?

Thanks, but I use version 8.9.2
```
vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020
```

**Comment by jcupitt** [comment]
Ooops, sorry, it should be:

```python
x = pyvips.Image.thumbnail("3198.gif[n=-1]", 128)
```

**Comment by zhaohuxing** [comment]
> Ooops, sorry, it should be:
> 
> ```python
> x = pyvips.Image.thumbnail("3198.gif[n=-1]", 128)
> ```

Thanks,
BTW, what does `n=-1` mean? I call thumbnail("3198.gif", 128) without `n=-1`, produced gif picture is static.

**Comment by jcupitt** [comment]
Sorry, I should not post untested code.

Here's a complete working program to thumbnail URLs, including animated images:

```python
#!/usr/bin/python3

# test with:
# https://upload.wikimedia.org/wikipedia/en/b/b4/Sceicbia.jpg
# https://upload.wikimedia.org/wikipedia/commons/6/69/F4-motion.gif

import sys
import requests
import pyvips

def loader_from_buffer(buf):
    image = pyvips.Image.new_from_buffer(buf, "")
    return image.get("vips-loader").split("_")[0]

image_url = sys.argv[1]
target_width = 128
buf = requests.get(image_url).content
loader = loader_from_buffer(buf)
options = ""
if loader == "gifload" or loader == "webpload":
    # an animated format -- make a thumbnail of all frames
    options = "n=-1"
thumb = pyvips.Image.thumbnail_buffer(buf, target_width, option_string=options)
thumb.write_to_file(sys.argv[2])
```

**Comment by jcupitt** [comment]
When you load an animated image, pyvips will just give you the first frame. You can select the number of frames to load with `n=` (1 meaning load 1 frame) and the first frame to load with `page=` (default 0, the first frame).

`n=-1` means load all frames.

**Comment by zhaohuxing** [comment]
@jcupitt If I did not call thumbnail function, use magick save the picture of gif format, how does resize this picture?
In the background, I use bimg library, but it isn't supported gif; so I not known how to modify bimg for supported gif.

**Comment by jcupitt** [comment]
I would use `thumbnail`. It has the extra logic for resizing animated images.

**Comment by zhaohuxing** [comment]
@jcupitt Can you provide a complete c program?

**Comment by jcupitt** [comment]
I had this example, it might help:

```C
/* Compile with:
 *
 * gcc -g -Wall buffer.c `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <stdlib.h>

#include <vips/vips.h>

int
main( int argc, char **argv )
{
	char *buffer_in;
	size_t length_in;
	GError *error = NULL;
	VipsImage *image, *x;
	char *buffer_out;
	size_t length_out;

	if( VIPS_INIT( argv[0] ) )
		vips_error_exit( NULL );

	/* Load source image into memory. This image will be in some format,
	 * like JPEG.
	 */
	if( !g_file_get_contents( argv[1], &buffer_in, &length_in, &error ) ) {
		fprintf( stderr, "unable to read file %s\n%s\n", 
			argv[1], error->message );
		g_error_free( error );
		exit( 1 );
	}

	/* Make a vips image from the memory buffer. This image will
	 * decompress from buffer_in as required.
	 */
	if( !(image = vips_image_new_from_buffer( buffer_in, length_in, NULL, 
		"access", VIPS_ACCESS_SEQUENTIAL,
		NULL )) ) 
		vips_error_exit( NULL );

	/* Perform some operation on the image.
	 */
	if( vips_invert( image, &x, NULL ) )
		vips_error_exit( NULL );

	/* x now holds a reference to image, so we can drop image and update
	 * our pointer to point to the head of the pipeline.
	 *
	 * buffer_in will still be in use -- we can't free that until the
	 * whole pipeline completes.
	 */
	g_object_unref( image );
	image = x;

	/* Create an output memory buffer. Again, this buffer will contain an
	 * image packed into some format, it will not be an array of pixel
	 * values.
	 */
	if( vips_image_write_to_buffer( image, 
		".jpg", (void **) &buffer_out, &length_out, NULL ) ) 
		vips_error_exit( NULL );

	if( !g_file_set_contents( argv[2], buffer_out, length_out, &error ) ) {
		fprintf( stderr, "unable to write file %s\n%s\n", 
			argv[1], error->message );
		g_error_free( error );
		exit( 1 );
	}

	g_object_unref( image ); 

	g_free( buffer_in );
	g_free( buffer_out );

	return( 0 );
}
```

**Comment by zhaohuxing** [comment]
@jcupitt Thanks

**Comment by zhaohuxing** [comment]
> When you load an animated image, pyvips will just give you the first frame. You can select the number of frames to load with `n=` (1 meaning load 1 frame) and the first frame to load with `page=` (default 0, the first frame).
> 
> `n=-1` means load all frames.

Hi @jcupitt, 
I use `thumbnail` to resize picture of the GIF format from c, `vips_thumbnail("new.gif[n=-1]", out, 200)`. If I use `vips_thumbnail_buffer`, how to set `n=-1`?

**Comment by jcupitt** [comment]
There's an argument called `option_string` you can use to pass extra flags to the loader. In C:

```C
vips_thumbnail_buffer( data, length, &image, 200, "option_string", "n=-1", NULL )
```

Now I look at the docs I see we'd forgotton to add a note about this extra argument. I've fixed it, thanks!

**Comment by zhaohuxing** [comment]
> There's an argument called `option_string` you can use to pass extra flags to the loader. In C:
> 
> ```c
> vips_thumbnail_buffer( data, length, &image, 200, "option_string", "n=-1", NULL )
> ```
> 
> Now I look at the docs I see we'd forgotten to add a note about this extra argument. I've fixed it, thanks!

Hi @jcupitt ,  I try to this the way, but the reduced image is static. `n = -1` does not seem to take effect. This is my complete program:
```
package main

/*
#cgo pkg-config: vips
#include <stdio.h>
#include <vips/vips.h>

int resize_image(void *buf, size_t len, int width) {
	VipsImage *out;

	vips_thumbnail_buffer(buf, len, &out, width, "option_string", "n=-1", NULL);

	if (vips_image_write_to_file( out, "brush_2.gif", NULL))
		vips_error_exit( NULL );
	g_object_unref( out );
}
*/
import "C"

import (
	"fmt"
	"io/ioutil"
	"unsafe"
)

func main() {
	buf, err := ioutil.ReadFile("brush.gif")
	if err != nil {
		panic(err)
	}

	length := C.size_t(len(buf))
	imageBuf := unsafe.Pointer(&buf[0])

	fmt.Printf("length: %d, buf: %v", length, imageBuf)
	C.resize_image(imageBuf, length, C.int(200))
}
```

**Comment by jcupitt** [comment]
It works for me. Perhaps there's something wrong with your GIF? You need to check the return code from `thumbnail_buffer`.

Test program:

```C
/* compile with
 *
 * gcc -g -Wall zhaohuxing.c `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>

int
main(int argc, char *argv[])
{
        char *contents;
        size_t length;
        VipsImage *image;

        if (VIPS_INIT (argv[0]))
                vips_error_exit (NULL);

        if (!g_file_get_contents (argv[1], &contents, &length, NULL))
                vips_error_exit (NULL);

        if (vips_thumbnail_buffer (contents, length, &image, 100,
                "option_string", "n=-1",
                NULL))
                vips_error_exit (NULL);

        if (vips_image_write_to_file (image, argv[2], NULL))
                return -1;

        g_free (contents);

        return 0;
}
```

I see:

```
$ ./a.out ~/pics/dancing-banana.gif x.gif
$ vipsheader ~/pics/dancing-banana.gif x.gif
temp-0: 121x128 uchar, 4 bands, srgb, gifload
temp-0: 95x100 uchar, 4 bands, srgb, gifload
```

Generating:

![x](https://user-images.githubusercontent.com/580843/81682881-37560b80-944d-11ea-9b98-4867a6c12aa6.gif)

**Comment by zhaohuxing** [comment]
Hi, @jcupitt
I use vips_thumbnail_buffer with the image of the GIF format，but How to write the processed picture to buffer from c. I tried to `vips_image_write_to_buffer` and `vips_magicksave_buffer`, both failed.

**Comment by jcupitt** [comment]
You need to give magicksave_buffer the format to encode in, eg.:

```C
        if (vips_magicksave_buffer (image,
                &output_contents, &output_length, 
                "format", "GIF",
                NULL))
                vips_error_exit (NULL);
```

**Comment by zhaohuxing** [comment]
> You need to give `vips_magicksave_buffer()` the format to encode in, eg.:
> 
> ```c
>         if (vips_magicksave_buffer (image,
>                 &output_contents, &output_length, 
>                 "format", "GIF",
>                 NULL))
>                 vips_error_exit (NULL);
> ```

I truly appreciate your timely help

**Comment by zhaohuxing** [comment]
Hi @jcupitt,  use `vips_image_new_from_buffer` init image in gif format, option_str set `n=-1`?

**Comment by jcupitt** [comment]
Yes, like the example above (if I understand what you mean).

**Comment by zhaohuxing** [comment]
Thanks @jcupitt
