### ISSUE TITLE
`rot()` results in an invalid image

### ISSUE THREAD

**Issue by scossu** [libvips/pyvips#160]
I am processing a source TIF and saving it as a pyramidal TIFF with JPEG compression. 

As I introduce a `rot()` command (actually `autorot()`, but I verified that `rot()` behaves the same way) I can no longer save the image. 

E.g. 

```
img = vips.Image.new_from_buffer(data.read(), "", access="sequential")
# further processing...

img = img.rot('d90')
# further processing...

kw = {
    "compression": "jpeg",
    "Q": 90,
    "profile": profile_fpath,
    "tile": True,
    "tile_width": 256,
    "tile_height": 256,
    "pyramid": True,
    "bigtiff": True,
}

return BytesIO(img.tiffsave_buffer(**kw))
```

This results in the following: 

```
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
VipsJpeg: out of order read at line 3024
Traceback (most recent call last):
  File "/usr/local/gcis/src/gcis/tools/image.py", line 141, in image_to_ptiff
    return BytesIO(img.tiffsave_buffer(**kw))
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 919, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyvips/voperation.py", line 282, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call tiffsave_buffer
  VipsJpeg: out of order read at line 3024
```

Without the `rot()` command, the image saves correctly.

Am I using the command correctly?

**Comment by scossu** [comment]
@princessmiracle Watch for downstream changes.

**Comment by jcupitt** [comment]
Hello @scossu,

You need to turn off `access="sequential"` if you are doing things like `rot()`.

There are some notes about this in the docs:

https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html#sequential-access

**Comment by scossu** [comment]
That works. Sorry for not catching that earlier.

**Comment by jcupitt** [comment]
No problem!
