### ISSUE TITLE
how to get associated image and call dzsave from python

### ISSUE THREAD

**Issue by renexu** [libvips/pyvips#165]
Just wondering if there are APIs in pyvips to do like
`vips openslideload --associated thunbmail ...`
and 
`vips dzsave`

**Comment by jcupitt** [comment]
Hello @renexu,

Sure, try:

```python
image = pyvips.Image.new_from_file("myslide.svs", associated="thumbnail")
image.dzsave("something")
```

**Comment by renexu** [comment]
awesome, thank you @jcupitt

**Comment by wangxinhui** [comment]
import pyvips

img = pyvips.Image.new_from_file('D:\\19970002-He.svs', associated="label")
img.dzsave('img123')

```Traceback (most recent call last):
  File "D:/pythonSpace/libvips/test.py", line 3, in <module>
    img = pyvips.Image.new_from_file('D:\\19970002-He.svs', associated="label")
  File "D:\pythonSpace\libvips\venv\lib\site-packages\pyvips\vimage.py", line 352, in new_from_file
    return pyvips.Operation.call(name, filename,
  File "D:\pythonSpace\libvips\venv\lib\site-packages\pyvips\voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignLoadTiffFile does not support optional argument associated

It doesn't work. help me.

**Comment by jcupitt** [comment]
Your libvips is missing openslide support. You need to download the `-all` version:

https://github.com/libvips/build-win64-mxe/releases/download/v8.13.3/vips-dev-w64-all-8.13.3.zip
