### ISSUE TITLE
Fails on 32-bit machines

### ISSUE THREAD

**Issue by dqxpb** [libvips/pyvips#171]
_Tried latest libvips+pyvips releases, then current masters, on **ARMv7** (Python 3.8.2) and finally on clean Debian **i686** (Python 3.7.3) [Glib 2.64/2.58, CFFI 1.14.0, pycparser 2.20]._

Installing pyvips finishes without errors in ABI mode yet fails on 'import pyvips'. Similar exceptions occur on 'python pyvips/pyvips_build.py':
**pycparser.plyparser.ParseError: <cdef source string>:5:29: before: GType                    
...
cffi.CDefError: cannot parse "typedef guint32 GType;"
<cdef source string>:5:29: before: GType**

Unfortunately after trying for a while - couldn't manage to fix this myself therefore would be grateful for some help. Thank you for great project!

Just in case here is full traceback of errors when running pyvips on 32-bit architecture:
```
Traceback (most recent call last):                                                          
  File "/usr/lib/python3.8/site-packages/cffi/cparser.py", line 305, in _parse              
    ast = _get_parser().parse(fullcsource)                                                  
  File "/usr/lib/python3.8/site-packages/pycparser/c_parser.py", line 149, in parse         
    return self.cparser.parse(                                                              
  File "/usr/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 331, in parse         
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)                  
  File "/usr/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notr
ack                                                                                         
    tok = call_errorfunc(self.errorfunc, errtoken, self)                                    
  File "/usr/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)                                                                    
  File "/usr/lib/python3.8/site-packages/pycparser/c_parser.py", line 1858, in p_error      
    self._parse_error(                                                                      
  File "/usr/lib/python3.8/site-packages/pycparser/plyparser.py", line 67, in _parse_error  
    raise ParseError("%s: %s" % (coord, msg))                                               
pycparser.plyparser.ParseError: <cdef source string>:5:29: before: GType                    
                                                                                            
During handling of the above exception, another exception occurred:                         
                                                                                            
Traceback (most recent call last):                                                          
  File "pyvips_build.py", line 48, in <module>                                              
    ffibuilder.cdef(vdecls.cdefs(features))                                                 
  File "/usr/lib/python3.8/site-packages/cffi/api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "/usr/lib/python3.8/site-packages/cffi/api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib/python3.8/site-packages/cffi/cparser.py", line 358, in parse
    self._internal_parse(csource)
  File "/usr/lib/python3.8/site-packages/cffi/cparser.py", line 363, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib/python3.8/site-packages/cffi/cparser.py", line 307, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib/python3.8/site-packages/cffi/cparser.py", line 336, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "typedef guint32 GType;"
<cdef source string>:5:29: before: GType
```

**Comment by jcupitt** [comment]
Hi, thanks for the report. It looks like a typedef was missing. 

Could you try git master pyvips?

**Comment by dqxpb** [comment]
Thanks a lot - working great!

**Comment by jcupitt** [comment]
Great! Thanks for testing.
