### ISSUE TITLE
TypeError when using autofit_dpi in Image.text

### ISSUE THREAD

**Issue by vphill** [libvips/pyvips#178]
This is going to most likely be user error, but I ran into this today. 

I was working with adding text to an image and was looking at the documentation here. 
https://libvips.github.io/pyvips/vimage.html#pyvips.Image.text

I saw `autofit_dpi` and thought that sounded useful.

When I tried it using this example, it gave me an error. 
https://github.com/libvips/pyvips/blob/master/examples/try12.py

Specifically, I adjusted this line
https://github.com/libvips/pyvips/blob/master/examples/try12.py#L10

```python
left_text = pyvips.Image.text("left corner", dpi=300)
```
to
```python
left_text = pyvips.Image.text("left corner", autofit_dpi=True)
```
but I ended up getting this error when I ran the modified example script.

```python
Traceback (most recent call last):
  File "example_12.py", line 9, in <module>
    footer = footer.insert(left_text, 50, 50)
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 919, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyvips/voperation.py", line 260, in call
    op.set(name, intro.details[name]['flags'], match_image, value)
  File "/usr/local/lib/python3.7/site-packages/pyvips/voperation.py", line 193, in set
    value = pyvips.Image._imageize(match_image, value)
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 157, in _imageize
    return self.new_from_image(value)
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 463, in new_from_image
    pixel = (Image.black(1, 1) + value).cast(self.format)
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 1015, in __add__
    return self.linear(1, other)
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 919, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyvips/voperation.py", line 260, in call
    op.set(name, intro.details[name]['flags'], match_image, value)
  File "/usr/local/lib/python3.7/site-packages/pyvips/voperation.py", line 204, in set
    super(Operation, self).set(name, value)
  File "/usr/local/lib/python3.7/site-packages/pyvips/vobject.py", line 112, in set
    gv.set(value)
  File "/usr/local/lib/python3.7/site-packages/pyvips/gvalue.py", line 186, in set
    array = ffi.new('double[]', value)
TypeError: must be real number, not Image
```
I also tried it with keeping `dpi=300` and still got the same error. 

Thank you for any suggestions.

**Comment by jcupitt** [comment]
Hi, you use it like this:

```python3
$ python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.text("hello", width=100, height=100, autofit_dpi=True)
>>> x
[<pyvips.Image 100x35 uchar, 1 bands, multiband>, {'autofit_dpi': 268}]
>>> 
```

So you get an extra item in the return. 

```
>>> image, options = pyvips.Image.text("hello", width=100, height=100, autofit_dpi=True)
>>> options['autofit_dpi']
268
```

**Comment by vphill** [comment]
Ah that makes sense. 

Thank you.
