### ISSUE TITLE
pyvips occured VipsForeignLoad

### ISSUE THREAD

**Issue by Jimmy-Tsai** [libvips/pyvips#196]
I installed libvips on Ubuntu 20.04 by 'vips-8.10.0.tar.gz' and install pyvips with pip. Then `import pyvips` can work in Python 3.6 but cann't read any images,  even `jpeg` or `png`
>  import pyvips
> pyvips.Image.new_from_file('/home/caibojun/Workspace/test.tiff')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/pyvips/vimage.py", line 226, in new_from_file
>     raise Error('unable to load from file {0}'.format(vips_filename))
> pyvips.error.Error: unable to load from file b'/home/caibojun/Workspace/test.tiff'
>   VipsForeignLoad: "/home/caibojun/Workspace/test.tiff" is not a known file format

**Comment by jcupitt** [comment]
Hello @Jimmy-Tsai,

8.10 is not officially released yet, I would use 8.9.2 for now.

When you compile it, you need to make sure it has headers for all of the file format libraries. You need to check the table it prints at the end of configure. You'll need to add packages like `libtiff-dev`.

**Comment by jcupitt** [comment]
You could also simply use the libvips that Ubuntu include. Try:

```
apt install libvips-dev
```
