### ISSUE TITLE
Created new .tif pyramid image from jpg image doesn't have more than 1 series while viewing it's property in python-bioformats.

### ISSUE THREAD

**Issue by Yuvi-416** [libvips/pyvips#222]
Hi there,
I have downloaded some jpg image from here: http://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu-vms/CMU-2.zip
And i pass below code to convert them into tif with pyramid option true. 
```
import pyvips
image = pyvips.Image.new_from_file(input_path)
image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")
```
When i visualize this image in openslide, i can view it has series of dimensions as below:
**level_dimensions: ((61440, 61440), (30720, 30720), (15360, 15360), (7680, 7680), (3840, 3840), (1920, 1920), (960, 960), (480, 480), (240, 240), (120, 120))**

But when i pass the same output to **python-bioformats**, it just shows first level (61440, 61440) but not all.
What's the problem? Is it the problem with image or with the bioformats.
**code to read image using bioformats:**
```
# setup reader
reader = bioformats.ImageReader(input_any1)
omeMeta = bioformats.metadatatools.createOMEXMLMetadata()
reader.setMetadataStore(omeMeta)
reader.setId(input_any1)
metadata = javabridge.jdictionary_to_string_dictionary(reader.rdr.getMetadata())
get = reader.rdr.getSeriesCount(input_any1)
gett = reader.rdr.getImageCount(input_any1)
```
I even run bftools to check the info of this image and it shows that, image has just one dimensions:
```
Checking file format [Tagged Image File Format]
Initializing reader
TiffDelegateReader initializing x.tif
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Initialization took 0.876s

Reading core metadata
filename = /Users/yubraj/Desktop/urgent_wsi/input/x.tif
Series count = 1
Series #0 :
	Image count = 1
	RGB = true (3) 
	Interleaved = false
	Indexed = false (false color)
	Width = 61440
	Height = 61440
	SizeZ = 1
	SizeT = 1
	SizeC = 3 (effectively 1)
	Thumbnail size = 128 x 128
	Endianness = intel (little)
	Dimension order = XYCZT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0

Reading global metadata
BitsPerSample: 8
Compression: JPEG
ImageLength: 61440
ImageWidth: 61440
MetaDataPhotometricInterpretation: RGB
MetaMorph: no
NumberOfChannels: 3
Orientation: 1st row - top; 1st column - left
PhotometricInterpretation: YCbCr
PlanarConfiguration: Chunky
ReferenceBlackWhite: 0
ResolutionUnit: Centimeter
SampleFormat: unsigned integer
SamplesPerPixel: 3
TileByteCounts: 991
TileLength: 128
TileOffsets: 8
TileWidth: 128
XResolution: 28.346456654716977
YResolution: 28.346456654716977
```
i even tried the code which is suggested here, but output is same:
https://github.com/libvips/libvips/issues/1365

I am doing all this in python environment.
Any suggestion

**Comment by jcupitt** [comment]
Hi @Yuvi-416,

bioformats only reads subifd pyramids. Try:

```python
image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg", subifd=True)
```

You'll need libvips 8.10, I think.

**Comment by Yuvi-416** [comment]
Hello there,
Thanks for your quick reply,
```
import pyvips; print("pyvips version: {}".format(pyvips.__version__))
input_path = "/home/yuvi/Downloads/DATASET/1-channel-example/vms/2/2.jpg"
image = pyvips.Image.new_from_file(input_path)
# image.write_to_file("1112.tif", pyramid=True, tile=True, compression="jpeg")
image.write_to_file("2-jpg.tif", pyramid=True, tile=True, compression="jpeg", subifd=True)
```
I ran the above code but the output is still the same.
I just installed vips-8-10.5 in my Linux pc.
I also ran: 
`vips copy /home/yuvi/Downloads/DATASET/1-channel-example/vms/2/2.jpg x.tif[pyramid,tile,compression=jpeg]
`
but again output was same, bioformats can't read another series.
Any further suggestion

**Comment by jcupitt** [comment]
Did you try the demo image?

**Comment by Yuvi-416** [comment]
Yeah,
I tried the code which u have posted above with that demo image and it didn't work.
```
input_path = "/home/yuvi/Downloads/DATASET/1-channel-example/vms/2/OS-2.tif"
image = pyvips.Image.new_from_file(input_path)
image.write_to_file("3-jpg.tif", pyramid=True, tile=True, compression="jpeg", subifd=True)
```
```
output:
level_dimension: (7936, 4608)
```
When i pass subifd=True, then image is not wrriten in a pyramid style.
But when i pass the code which u wrote above without subifd=True option then image is written in pyramid structure and i can confirm it has a pyramid structure by loading it within a openslide but when i load same image using python-bioformats it just shows 1 level.
```
image = pyvips.Image.new_from_file(input_path)
image.write_to_file("4-jpg.tif", pyramid=True, tile=True, compression="jpeg")
Output:
level_dimension = ((7936, 4608), (3968, 2304), (1984, 1152), (992, 576), (496, 288), (248, 144), (124, 72))
```
Am i missing something?

**Comment by jcupitt** [comment]
<blockquote>
When i pass subifd=True, then image is not wrriten in a pyramid style.
</blockquote>

Are you sure? It's working for me. I see:

```
$ vips copy k2.jpg x.tif[pyramid=True,tile=True,compression="jpeg",subifd=True]
$ tiffinfo x.tif 
TIFF Directory at offset 0x386b6 (231094)
  Image Width: 1450 Image Length: 2048
  Tile Width: 128 Tile Length: 128
  Resolution: 72.009, 72.009 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  SubIFD Offsets: 310260 336348 346306 350350
  JPEG Tables: (574 bytes)
```

The other pyramid layers are in the subifds 310260 336348 346306 350350. For example:

```
$ tiffinfo x.tif -o 310260
TIFF Directory at offset 0x4bbf4 (310260)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 725 Image Length: 1024
  Tile Width: 128 Tile Length: 128
  Resolution: 72.009, 72.009 pixels/inch
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  JPEG Tables: (574 bytes)
```

**Comment by Yuvi-416** [comment]
Hi,
Sorry for late reply.
Okay, it work but now i have a big confusion.
I think you can help me to clear it.
**First, i tried your suggestion as below:**
```
(base) yuvi@yuvi-lfc:~/Downloads/DATASET/1-channel-example/vms/2$ vips copy 2.jpg 123.tif[pyramid=True,tile=True,compression="jpeg",subifd=True]
(base) yuvi@yuvi-lfc:~/Downloads/DATASET/1-channel-example/vms/2$ tiffinfo 123.tif
TIFF Directory at offset 0x147b4bf4 (343624692)
  Image Width: 61440 Image Length: 61440
  Tile Width: 128 Tile Length: 128
  Resolution: 28.3465, 28.3465 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  SubIFD Offsets: 449712420 481867978 490993138 493436000 494038120 494185438 494222630 494232902 494236438
  JPEG Tables: (574 bytes)

```
when i load 123.tif image using openslide i get this as output:
![Screenshot from 2020-12-19 17-52-02](https://user-images.githubusercontent.com/65744819/102696002-15163e80-4223-11eb-907c-6483cca8eb1c.png)
As you can see in above picture that, openslide just shows 1 dimensions (61440, 61440).
And like wise openslide, python-bioformat also only shows 1 dimesnions as (61440, 61440).

But when, i try below code to convert it into tiff and when i visualize that converted image in openslide, it shows all dimensions as shown in a below picture:
```
image = pyvips.Image.new_from_file(input_path)
image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")
```
![Screenshot from 2020-12-19 17-59-06](https://user-images.githubusercontent.com/65744819/102696139-0419fd00-4224-11eb-86f7-cb7b0b1be02e.png)

But the problem is whatever tif image i pass to the python-bioformat, but it only shows first level.
![Screenshot from 2020-12-19 18-04-18](https://user-images.githubusercontent.com/65744819/102696241-c669a400-4224-11eb-8d32-a07acfde2f05.png)
For example, i pass the image which i have convert using vips copy as above, but the gerseriescount is still 1.

**Comment by jcupitt** [comment]
openslide doesn't know about ifd pyramids --- they are a bioformats thing. You need to use something like qupath to test them.

How are you trying to load into bioformats?

**Comment by Yuvi-416** [comment]
Utilizing the below code. I haven't installed qupath so far and basically, my current working environment is in python so I didn't try other than it. But the below code can read ndpi, svs, scn images but not .tif extension. I can't understand why it's not reading other series beside first.
```
import bioformats
from bioformats import ImageReader, OMETiffWriter
import javabridge
import javabridge as jutil
from PIL import Image
import bioformats.omexml as OME

input_any1 = "/home/yuvi/Downloads/DATASET/1-channel-example/vms/2/123.tif"
output_save_per_channel = "/home/yuvi/openslide-samples/"

Image.MAX_IMAGE_PIXELS = None
javabridge.start_vm(class_path=bioformats.JARS, max_heap_size="9G")
env = jutil.attach()

###############################
# setup reader
###############################
reader = bioformats.ImageReader(input_any1)
omeMeta = bioformats.metadatatools.createOMEXMLMetadata()
reader.setMetadataStore(omeMeta)
reader.setId(input_any1)
metadata = javabridge.jdictionary_to_string_dictionary(reader.rdr.getMetadata())
get = reader.rdr.getSeriesCount(input_any1)
gett = reader.rdr.getImageCount(input_any1)
################################
jutil.detach()
javabridge.kill_vm()
```

**Comment by jcupitt** [comment]
Here's that test python converter again --- all it does is split the image into planes (OME-TIFF does not support interleaved images, you can only have one channel per image) and set some minimal XML for bioformats:

```python
#!/usr/bin/python3

import sys
import pyvips

im = pyvips.Image.new_from_file(sys.argv[1])

# openslide will add an alpha ... drop it
if im.hasalpha():
    im = im[:-1]

image_height = im.height
image_bands = im.bands

# reorganise as a toilet-roll image
im = pyvips.Image.arrayjoin(im.bandsplit(), across=1)

# set minimal OME metadata
# before we can modify an image (set metadata in this case), we must take a 
# private copy
im = im.copy()
im.set_type(pyvips.GValue.gint_type, "page-height", image_height)
im.set_type(pyvips.GValue.gstr_type, "image-description",
f"""<?xml version="1.0" encoding="UTF-8"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
    <Image ID="Image:0">
        <!-- Minimum required fields about image dimensions -->
        <Pixels DimensionOrder="XYCZT"
                ID="Pixels:0"
                SizeC="{image_bands}"
                SizeT="1"
                SizeX="{im.width}"
                SizeY="{image_height}"
                SizeZ="1"
                Type="uint8">
        </Pixels>
    </Image>
</OME>""")

im.tiffsave(sys.argv[2], compression="jpeg", tile=True,
            tile_width=512, tile_height=512,
            pyramid=True, subifd=True)
```

If I run:

```
$ ~/try/convert.py nina.jpg x.ome.tiff
```

And then `showinf`, I see:

```
$ ~/packages/bioformats/bftools/showinf x.ome.tiff 
Checking file format [OME-TIFF]
Initializing reader
OMETiffReader initializing x.ome.tiff
SamplesPerPixel mismatch: OME=-1, TIFF=1
Image ID 'Image:0': missing plane #0
Image ID 'Image:0': missing plane #1
Image ID 'Image:0': missing plane #2
Using TiffReader to determine the number of planes.
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Initialization took 0.055s

Reading core metadata
filename = /home/john/pics/x.ome.tiff
Used files = [/home/john/pics/x.ome.tiff]
Series count = 5
Series #0 :
	Image count = 3
	RGB = false (1) 
	Interleaved = false
	Indexed = false (false color)
	Width = 6048
	Height = 4032
	SizeZ = 1
	SizeT = 1
	SizeC = 3
	Tile size = 512 x 512
	Thumbnail size = 128 x 85
	Endianness = intel (little)
	Dimension order = XYCZT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #1 <=> Z 0, C 1, T 0
	Plane #2 <=> Z 0, C 2, T 0

Series #1 :
	Image count = 3
	RGB = false (1) 
	Interleaved = false
	Indexed = false (false color)
	Width = 3024
	Height = 2016
	SizeZ = 1
	SizeT = 1
	SizeC = 3
	Tile size = 512 x 512
	Thumbnail size = 128 x 85
	Endianness = intel (little)
	Dimension order = XYCZT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #1 <=> Z 0, C 1, T 0
	Plane #2 <=> Z 0, C 2, T 0

Series #2 :
	Image count = 3
	RGB = false (1) 
	Interleaved = false
	Indexed = false (false color)
	Width = 1512
	Height = 1008
	SizeZ = 1
	SizeT = 1
	SizeC = 3
	Tile size = 512 x 512
	Thumbnail size = 128 x 85
	Endianness = intel (little)
	Dimension order = XYCZT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #1 <=> Z 0, C 1, T 0
	Plane #2 <=> Z 0, C 2, T 0

Series #3 :
	Image count = 3
	RGB = false (1) 
	Interleaved = false
	Indexed = false (false color)
	Width = 756
	Height = 504
	SizeZ = 1
	SizeT = 1
	SizeC = 3
	Tile size = 512 x 512
	Thumbnail size = 128 x 85
	Endianness = intel (little)
	Dimension order = XYCZT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #1 <=> Z 0, C 1, T 0
	Plane #2 <=> Z 0, C 2, T 0

Series #4 :
	Image count = 3
	RGB = false (1) 
	Interleaved = false
	Indexed = false (false color)
	Width = 378
	Height = 252
	SizeZ = 1
	SizeT = 1
	SizeC = 3
	Tile size = 512 x 512
	Thumbnail size = 128 x 85
	Endianness = intel (little)
	Dimension order = XYCZT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #1 <=> Z 0, C 1, T 0
	Plane #2 <=> Z 0, C 2, T 0


Reading series #0 pixel data (0-2)
	Read 3/3 planes (100%)
[done]
0.537s elapsed (179.0ms per plane)
```

So you can see it's founf the pyramids layers and the image channels. I expect you could set some XML to get it tagged as an RGB image and displayed in colour.

**Comment by Yuvi-416** [comment]
Hi,
I tried the code which you have posted above and I got the output but when i pass showing command of bftools to visualize it's layer. It shows some error.
Code:
```
import sys
import pyvips
input_path = "/home/yuvi/Downloads/DATASET/1-channel-example/vms/3/3.jpg"

im = pyvips.Image.new_from_file(input_path)

# openslide will add an alpha ... drop it
if im.hasalpha():
    im = im[:-1]

image_height = im.height
image_bands = im.bands

# reorganise as a toilet-roll image
im = pyvips.Image.arrayjoin(im.bandsplit(), across=1)

# set minimal OME metadata
# before we can modify an image (set metadata in this case), we must take a
# private copy
im = im.copy()
im.set_type(pyvips.GValue.gint_type, "page-height", image_height)
im.set_type(pyvips.GValue.gstr_type, "image-description",
f"""<?xml version="1.0" encoding="UTF-8"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
    <Image ID="Image:0">
        <!-- Minimum required fields about image dimensions -->
        <Pixels DimensionOrder="XYCZT"
                ID="Pixels:0"
                SizeC="{image_bands}"
                SizeT="1"
                SizeX="{im.width}"
                SizeY="{image_height}"
                SizeZ="1"
                Type="uint8">
        </Pixels>
    </Image>
</OME>""")

im.tiffsave("xxx.ome.tiff", compression="jpeg", tile=True,
            tile_width=512, tile_height=512,
            pyramid=True, subifd=True)
```
And below is the error given by bftools:
```
Checking file format [OME-TIFF]
Initializing reader
OMETiffReader initializing /Users/yubraj/Desktop/urgent_wsi/input/xxx.ome.tiff
SamplesPerPixel mismatch: OME=-1, TIFF=1
Image ID 'Image:0': missing plane #0.  Using TiffReader to determine the number of planes.
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at loci.formats.MetadataTools.populatePixelsOnly(MetadataTools.java:293)
	at loci.formats.MetadataTools.populateMetadata(MetadataTools.java:251)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:151)
	at loci.formats.in.OMETiffReader.initFile(OMETiffReader.java:1022)
	at loci.formats.FormatReader.setId(FormatReader.java:1397)
	at loci.formats.ImageReader.setId(ImageReader.java:839)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1031)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1117)
```
Can you try to convert this image in your machine and check the output?
https://uapt33090-my.sharepoint.com/:i:/g/personal/ygupta_ua_pt/Eap2ID-LR6tOg2iqgPhgvIQBPgTC7mDv0YDMh_PwoazqdA?e=Dhw3k6
And this is the output which my machine generate:
https://uapt33090-my.sharepoint.com/:i:/g/personal/ygupta_ua_pt/ETNY32yW7nlHjFS8fNLeGa8BUr9wJvkIfXwyJBELDbbiNQ?e=aPinQB

Can you please check it?
And what do you mean by "I expect you could set some XML to get it tagged as an RGB image and displayed in colour ". I didn't understand this line.

**Comment by jcupitt** [comment]
I'd guess you've not set the XML correctly. You'll need to check the bioformats docs.

I ran the sample program like this (the JPG is a pic of one of my kids):

```
./convert.py ~/pics/nina.jpg x.tif
```

To make:

http://www.rollthepotato.net/~john/x.tif

It loads into QuPath like this:

```
$ ./QuPath-0.2.3 ~/try/x.tif
...
12:38:15.781 [JavaFX Application Thread] [WARN ] loci.formats.FormatHandler - Using TiffReader to determine the number of planes.
12:38:15.942 [region-store-1] [WARN ] loci.formats.FormatHandler - SamplesPerPixel mismatch: OME=-1, TIFF=1
12:38:15.942 [region-store-1] [WARN ] loci.formats.FormatHandler - Image ID 'Image:0': missing plane #0
12:38:15.942 [region-store-1] [WARN ] loci.formats.FormatHandler - Image ID 'Image:0': missing plane #1
12:38:15.942 [region-store-1] [WARN ] loci.formats.FormatHandler - Image ID 'Image:0': missing plane #2
12:38:15.942 [region-store-1] [WARN ] loci.formats.FormatHandler - Using TiffReader to determine the number of planes.
12:38:16.272 [JavaFX Application Thread] [INFO ] qupath.lib.gui.viewer.QuPathViewer - Image data set to ImageData: Not set, x.tif
```

And pops up a dialog warning about stuff not being set, but displays fine. I tried a six-band image and that worked too.

**Comment by Yuvi-416** [comment]
Hi, @jcupitt
Sorry for the late reply.
I am able to get the pyramid style image but the generated output doesn't seem correct.
You can check the input and generated output over here https://github.com/libvips/pyvips/issues/223
I don't know why the generated output is repeated for the only the first layer.
Do you have any suggestion?
