### ISSUE TITLE
pyvips.error.Error: thumbnail needs 2 arguments, but 1 given

### ISSUE THREAD

**Issue by derneuere** [libvips/pyvips#260]
Deployment with docker based on: python:3.8-slim-buster
libvips: 8.11 build from source
pyvips: 2.1.15

First, I just wanted to say, that your library is awesome! 

I get the following exception when trying to create a thumbnail with pyvips:
```python
2021-06-30 06:27:17,513 : thumbnails.py : createThumbnail : 7 : INFO : Create thumbnail of: /data/MissingPhoto/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg
2021-06-30 06:27:17,515 : directory_watcher.py : handle_new_image : 132 : ERROR : job ba3a3ba5-cacf-4b30-96e6-7a31d651d834: could not load image /data/MissingPhoto/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg. reason: thumbnail needs 2 arguments, but 1 given
  
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 103, in handle_new_image
    photo._generate_thumbnail(True)
  File "/code/api/models/photo.py", line 132, in _generate_thumbnail
    createThumbnail(inputPath=self.image_paths[0], outputHeight=1080, outputPath='thumbnails_big', hash=self.image_hash, fileType=".webp")
  File "/code/api/thumbnails.py", line 8, in createThumbnail
    x = pyvips.Image.thumbnail(inputPath, height=outputHeight)
  File "/usr/local/lib/python3.8/site-packages/pyvips/vimage.py", line 135, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyvips/voperation.py", line 225, in call
    raise Error('{0} needs {1} arguments, but {2} given'
pyvips.error.Error: thumbnail needs 2 arguments, but 1 given
```
This is my function:
```python
import pyvips
import os
import ownphotos.settings
from api.util import logger

def createThumbnail(inputPath, outputHeight, outputPath, hash, fileType):
    logger.info("Create thumbnail of: " + inputPath)
    x = pyvips.Image.thumbnail(inputPath, height=outputHeight)
    completePath = os.path.join(ownphotos.settings.MEDIA_ROOT, outputPath, hash + fileType).strip()
    x.write_to_file(completePath)
    return completePath
```
I have the correct version of pyvips:
```
pip shows pyvips
Name: pyvips
Version: 2.1.15
Summary: binding for the libvips image processing library, API mode
Home-page: https://github.com/libvips/pyvips
Author: John Cupitt
Author-email: jcupitt@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/site-packages
Requires: cffi, pkgconfig
Required-by: 
```
I have the correct version of vips:
```
vips -v
vips-8.11.0-Wed Jun  9 18:20:35 UTC 2021
```
I have also installed the correct packages.
```
vips --vips-config
enable debug: no
enable deprecated library components: yes
enable modules: yes
enable docs with gtkdoc: no
gobject introspection:  no
RAD load/save: yes
Analyze7 load/save: yes
PPM load/save: yes
GIF load:  yes
generate C++ docs: no
use fftw3 for FFT: no
accelerate loops with orc: yes
ICC profile support with lcms: yes (lcms2)
zlib: yes
text rendering with pangocairo: no
font file support with fontconfig: 
EXIF metadata support with libexif: yes
JPEG load/save with libjpeg: yes (pkg-config)
JXL load/save with libjxl: no (dynamic module: no)
JPEG2000 load/save with libopenjp2: no
PNG load with libspng: no
PNG load/save with libpng: yes (pkg-config libpng >= 1.2.9)
8bpp PNG quantisation: yes
TIFF load/save with libtiff: yes (pkg-config libtiff-4)
image pyramid save: yes
HEIC/AVIF load/save with libheif: yes (dynamic module: yes)
WebP load/save with libwebp: yes
PDF load with PDFium:  no
PDF load with poppler-glib: no (dynamic module: no)
SVG load with librsvg-2.0: yes
EXR load with OpenEXR: yes
slide load with OpenSlide: no (dynamic module: no)
Matlab load with matio: no
NIfTI load/save with niftiio: no
FITS load/save with cfitsio: yes
Magick package: MagickCore (dynamic module: yes)
Magick API version: magick6
load with libMagickCore: yes
save with libMagickCore: yes
```
There is no other version of libvips installed via apt
```
apt list --installed | grep libvips
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

```
I don't get which argument is missing or what I am doing wrong. Could you help me find out, what I am missing?

**Comment by jcupitt** [comment]
Hi @derneuere,

Thanks for your kind words. `thumbnail` needs a width parameter:

```
john@banana ~/pics $ python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.thumbnail("k2.jpg", 128, height=42)
>>> x.write_to_file("x.jpg")
>>> 
john@banana ~/pics $ vipsheader x.jpg
x.jpg: 30x42 uchar, 3 bands, srgb, jpegload
john@banana ~/pics $ 
```

So that's shrinking to fit within a 128x32 bounding box.

Docs are here:

https://libvips.github.io/pyvips/vimage.html#pyvips.Image.thumbnail

**Comment by jcupitt** [comment]
... and detailed docs for `thumbnail` are here:

https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

**Comment by derneuere** [comment]
Thank you! Now it works. Should have reread the docs :sweat_smile:
