### ISSUE TITLE
Image.asinh() not supported but is expected to be

### ISSUE THREAD

**Issue by acscott** [libvips/pyvips#301]
vimage.py has an asinh function but it's not in VipsOperationMath

```
Traceback (most recent call last):
  File "/home/adam/thumbs/exstamps.py", line 42, in <module>
    img = img.asinh()
  File "/usr/local/lib/python3.9/dist-packages/pyvips/vimage.py", line 1352, in asinh
    return self.math('asinh')
  File "/usr/local/lib/python3.9/dist-packages/pyvips/vimage.py", line 938, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyvips/voperation.py", line 282, in call
    op.set(name, intro.details[name]['flags'], match_image, value)
  File "/usr/local/lib/python3.9/dist-packages/pyvips/voperation.py", line 216, in set
    super(Operation, self).set(name, value)
  File "/usr/local/lib/python3.9/dist-packages/pyvips/vobject.py", line 112, in set
    gv.set(value)
  File "/usr/local/lib/python3.9/dist-packages/pyvips/gvalue.py", line 174, in set
    GValue.to_enum(gtype, value))
  File "/usr/local/lib/python3.9/dist-packages/pyvips/gvalue.py", line 110, in to_enum
    raise Error('no value {0} in gtype {1} ({2})'.
pyvips.error.Error: no value asinh in gtype VipsOperationMath (42283696)
  pyvips: enum 'VipsOperationMath' has no member 'asinh', should be one of: sin, cos, tan, asin, acos, atan, log, log10, exp, exp10
```

**Comment by jcupitt** [comment]
Hi @acscott,

I would guess your libvips is too old. You need libvips 8.12 or later for the hyperbolic trig functions.

**Comment by acscott** [comment]
Thank you John!  Indeed, I'm on 8.10.5-2ubuntu1.  Thanks for such a quick
response!
