### ISSUE TITLE
missing arguments in text 

### ISSUE THREAD

**Issue by gachiemchiep** [libvips/pyvips#331]
Hello @jcupitt 
Somehow the rgba parameter is missing from pyvips.Image.text. 
Would you mind take a look at this. 

Here is my log

```bash
(base) gachiemchiep:synthetic_db$ python3
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.text("hello!", width=100, height=150, dpi=300)
>>> x = pyvips.Image.text("hello!", width=100, height=150, dpi=300, rgba=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gachiemchiep/miniconda3/lib/python3.9/site-packages/pyvips/vimage.py", line 256, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "/home/gachiemchiep/miniconda3/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: text does not support optional argument rgba
```

Using the system python3 also leads to same problem

```bash
gachiemchiep:synthetic_db$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.text("hello!", width=100, height=150, dpi=300)
>>> x = pyvips.Image.text("hello!", width=100, height=150, dpi=300, rgba=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gachiemchiep/.local/lib/python3.8/site-packages/pyvips/vimage.py", line 256, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "/home/gachiemchiep/.local/lib/python3.8/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: text does not support optional argument rgba
```

I have libvips-dev 8.9.1-2 

```bash
(base) gachiemchiep:synthetic_db$ dpkg -l | grep libvips
ii  libvips-dev                                         8.9.1-2                                                          amd64        image processing system good for very large ones (dev)
ii  libvips-doc                                         8.9.1-2                                                          all          image processing system good for very large ones (doc)
ii  libvips-tools                                       8.9.1-2                                                          amd64        image processing system good for very large ones (tools)
ii  libvips42:amd64                                     8.9.1-2                                                          amd64        image processing system good for very large ones

```

**Comment by gachiemchiep** [comment]
Please ignore this issue. 

in libvips I found this line *libvips/libvips/create/text.c*

```bash
 * 12/4/21
 * 	- switch to cairo for text rendering
 * 	- add rgba flag
```

libvips 8.9.1.2 is 3 years old. So i switch to newer version 8.12. Then my problem is solved.
