### ISSUE TITLE
Is writing PNM file format not supported yet?

### ISSUE THREAD

**Issue by ewelot** [libvips/pyvips#381]
I recently switched to libvips version 8.14.1 which now supports writing PNM files (see e.g. [here](https://github.com/libvips/libvips/issues/3016)). Does it require an update of pyvips to get support for this in python? I am currently running pyvips 2.2.1 and get
```
Traceback (most recent call last):
  File "/home/lehmann/bin/home/airfun.py", line 1159, in <module>
    globals()[sys.argv[1]](sys.argv[2:])
  File "/home/lehmann/bin/home/airfun.py", line 1028, in writeimage
    image.write_to_target(target, "." + fmt, strip=strip)
  File "/usr/lib/python3/dist-packages/pyvips/vimage.py", line 915, in write_to_target
    raise Error('unable to write to target')
pyvips.error.Error: unable to write to target
  VipsForeignSave: ".pnm" is not a known target format
```
Thanks
Thomas

**Comment by jcupitt** [comment]
Hi @ewelot,

You're right, there's an error in 8.14, it's wasn't initing the pnm writer for targets.

With 8.14 head I now see:

```
$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = pyvips.Image.new_from_file("k2.jpg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pyvips' is not defined
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> y = x.write_to_buffer(".pnm")
>>> 
```

And target should work too. Thanks for reporting this!
