### ISSUE TITLE
TypeError: initializer for ctype 'char *' must be a cdata pointer, not TargetCustom

### ISSUE THREAD

**Issue by maqsudinamdar** [libvips/pyvips#391]
## Environment

- Vips: `vips-8.14.1`
- pyvips: 2.2.1        
    
---

## Problem Description

I'm trying streamline deepzoom generation process as supported with [libvips 8.9](https://www.libvips.org/2019/12/11/What's-new-in-8.9.html)

I've created `SourceCustom` and `TargetCustom` 

---
## Sample Code

```
import pyvips
from google.cloud import storage
from google.cloud.storage.fileio import BlobWriter, BlobReader
from pyvips import Image
from config import config

client = storage.Client(config.GOOGLE_PROJECT_NAME)
bucket = client.get_bucket(config.SOURCE_BUCKET)

read_file_path = "stitched_rois/roi_1234_0.jpeg"
read_blob = bucket.blob(read_file_path)
read_file: BlobReader = read_blob.open(mode="rb")

def read_handler(size):
    return read_file.read(size)

source = pyvips.SourceCustom()
source.on_read(read_handler)


write_file_path = "stitched_rois/test/12345"
write_blob = bucket.blob(write_file_path)
write_file: BlobWriter = write_blob.open(mode="wb")

def write_handler(chunk):
    return write_file.write(chunk)

def finish_handler():
    write_file.close()

target = pyvips.TargetCustom()
target.on_write(write_handler)
target.on_finish(finish_handler)


image: Image = pyvips.Image.new_from_source(source, '')
image.dzsave(target)
```
---

## Traceback:
```
Traceback (most recent call last):
  File "/Users/maksudinamdar/Documents/slide-composer/test.py", line 54, in <module>
    image.dzsave(target)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyvips/vimage.py", line 1347, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyvips/voperation.py", line 282, in call
    op.set(name, intro.details[name]['flags'], match_image, value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyvips/voperation.py", line 216, in set
    super(Operation, self).set(name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyvips/vobject.py", line 122, in set
    gv.set(value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyvips/gvalue.py", line 178, in set
    gobject_lib.g_value_set_string(self.gvalue, _to_bytes(value))
TypeError: initializer for ctype 'char *' must be a cdata pointer, not TargetCustom
```

**Comment by jcupitt** [comment]
Hi, try `dzsave_target`, or `write_to_target()`.

**Comment by maqsudinamdar** [comment]
Hi @jcupitt, Thanks for your quick response!  But, here the output is in `application/octet-stream` format rather `Folder` and `image/jpeg` inside it, as in the case of `dzsave`

<img width="1015" alt="Screenshot 2023-03-08 at 2 10 07 PM" src="https://user-images.githubusercontent.com/55288077/223664410-75df69af-3b28-4fa4-be5d-a51a69aa68b8.png">

**Comment by maqsudinamdar** [comment]
And @jcupitt , I think `write_to_target` won't work as i'm trying to create deepzoom file

**Comment by jcupitt** [comment]
`write_to_target` should work, just use `".dz"` as the format.

Targets are bytestreams, so you can't write directory trees to them. In this case, dzsave will write an uncompressed zip with all your stuff in. unzip that and you should have your tiles and directories.

**Comment by jcupitt** [comment]
I made you a tiny demo prog:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])

file = open(sys.argv[2], "wb")

def write_handler(chunk):
    return file.write(chunk)

# read and seek are optional and only needed for formats like TIFF
def read_handler(size):
    return file.read(size)

def seek_handler(offset, whence):
    file.seek(offset, whence)
    return file.tell()

def end_handler():
    # you can't throw exceptions over on_ handlers, you must return an
    # error code
    try:
        file.close()
    except IOError:
        return -1
    else:
        return 0

target = pyvips.TargetCustom()
target.on_write(write_handler)
#target.on_read(read_handler)
#target.on_seek(seek_handler)
#target.on_end(end_handler)

image.write_to_target(target, sys.argv[2])
```

It's using a custom target to write to a file, but it would be easy to mkake it wriote somewhere else.

I see:

```
$ ./targetsave.py ~/pics/k2.jpg x.dz
$ unzip ../x.dz
Archive:  ../x.dz
 extracting: untitled/untitled_files/11/3_0.jpeg  
 extracting: untitled/untitled_files/11/5_0.jpeg  
 extracting: untitled/untitled_files/11/0_0.jpeg  
 extracting: untitled/untitled_files/11/4_0.jpeg  
...
 extracting: untitled/untitled_files/8/0_1.jpeg  
 extracting: untitled/untitled.dzi   
 extracting: untitled/untitled_files/vips-properties.xml  
```

**Comment by maqsudinamdar** [comment]
Agree @jcupitt, But is there anyway to write directory trees on cloud storage. Because we still need to unzip it for using it.

**Comment by jcupitt** [comment]
Uploading 100,000 tiny files to the cloud will give pretty terrible performance, but if you must do that, then I would write to a local filesystem then do the upload.

A better solution is to upload the zip, then use http range requests to read tiles out of that in javascript in your client. Just define a new get-tile function for your leaflet/openseadragon/whatever viewer.

**Comment by maqsudinamdar** [comment]
But then also we need to unzip the files in cloud storage to return the requested range. Or, Can we still return portion of tiles without unzipping it?

**Comment by jcupitt** [comment]
Yes, http range requests let you read a small piece from a large file, so there's no need to unzip.
