### ISSUE TITLE
VipsOperation: class "dzsave" not found

### ISSUE THREAD

**Issue by Rasaa84** [libvips/pyvips#407]
Hi,

I have installed pyvips using pip on Windows 11 but get the following error calling dzsave. 

Traceback (most recent call last):
  File "C:\Users\...\anaconda3\envs\torch\lib\site-packages\pyvips\vimage.py", line 1339, in __getattr__
    Introspect.get(name)
  File "C:\Users\...\anaconda3\envs\torch\lib\site-packages\pyvips\voperation.py", line 153, in get
    cls._introspect_cache[operation_name] = Introspect(operation_name)
  File "C:\Users\...\anaconda3\envs\torch\lib\site-packages\pyvips\voperation.py", line 39, in __init__
    op = Operation.new_from_name(operation_name)
  File "C:\Users\...\anaconda3\envs\torch\lib\site-packages\pyvips\voperation.py", line 193, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation dzsave
  VipsOperation: class "dzsave" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\anaconda3\envs\torch\lib\site-packages\pyvips\vimage.py", line 1343, in __getattr__
    raise AttributeError
AttributeError

Any ideas what the issue is?

**Comment by jcupitt** [comment]
Hi, have you seen https://github.com/libvips/libvips/pull/3476 ?

We've had to remove dzsave from precompiled windows binaries due to licensing issues. It should come back soon. 

In the meantime, you can stick with an older libvips version, or build your own binary.
