### ISSUE TITLE
Re-using a filename causes "LZWDecode: Corrupted LZW table"

### ISSUE THREAD

**Issue by ido-nuc** [libvips/pyvips#420]
Hi, when using `pyvips` to save and blend tiff files, we encountered a weird behavior. Reusing a filename somehow corrupted the file, which was revealed only after trying to blend it, and only from within the same process.

The error is the following:
```
  File "/root/workspace/algo/tmptmp.py", line 26, in <module>
    blend_tiffs(["img3.tiff", "img_shared_filename.tiff"], "img_blended_2.tiff")
  File "/root/workspace/algo/tmptmp.py", line 8, in blend_tiffs
    composite.write_to_file(output_filename, pyramid=True, tile=True, compression="lzw", bigtiff=True)
  File "/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/pyvips/voperation.py", line 305, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignSaveTiffFile
  LZWDecode: Corrupted LZW table at scanline 128
LZWDecode: Corrupted LZW table at scanline 256
LZWDecode: Corrupted LZW table at scanline 384
```

This is a minimal reproduction code we came up with:
```
import numpy as np
import pyvips


def blend_tiffs(filenames: list[str], output_filename: str):
    first_image, *other_images = [pyvips.Image.new_from_file(filename, access="sequential") for filename in filenames]
    composite = first_image.composite(other_images, "over")
    composite.write_to_file(output_filename, pyramid=True, tile=True, compression="lzw", bigtiff=True)


def save_tiff(full_scale_image, file_name):
    vips_res = 1e3 / 0.5
    tiff_params = dict(pyramid=True, tile=True, bigtiff=True, xres=vips_res, yres=vips_res, compression="lzw")
    pyvips.Image.new_from_array(full_scale_image, interpretation="rgb").write_to_file(file_name, **tiff_params)


img1 = np.random.randint(0, 255, (1000, 1000, 4), dtype=np.uint8)
img2 = np.random.randint(0, 255, (1000, 1000, 4), dtype=np.uint8)
img3 = np.random.randint(0, 255, (500, 500, 4), dtype=np.uint8)
img4 = np.random.randint(0, 255, (500, 500, 4), dtype=np.uint8)
save_tiff(img1, "img1.tiff")
save_tiff(img2, "img_shared_filename.tiff")
blend_tiffs(["img1.tiff", "img_shared_filename.tiff"], "img_blended_1.tiff")
save_tiff(img3, "img3.tiff")
save_tiff(img4, "img_shared_filename.tiff")
blend_tiffs(["img3.tiff", "img_shared_filename.tiff"], "img_blended_2.tiff")
```

The above code fails on the last line. Stopping in debugger right before the failing line, and executing the exact same line (`blend_tiffs(...)`) from a separate python process works just fine.

vips versions we tested (both with pyvips 2.2.1):
* 8.9.1
* 8.14.2

We'll appreciate any help! Thanks in advance.

**Comment by jcupitt** [comment]
Hi @ido-nuc,

Huh, curious. I managed to make it a bit simpler:

```python
#!/usr/bin/env python

import numpy as np
import pyvips


def save_pyr(full_scale_image, file_name):
    image = pyvips.Image.new_from_array(full_scale_image)
    image.write_to_file(file_name, pyramid=True, compression="lzw")


def save_tif(filename, output_filename):
    image = pyvips.Image.new_from_file(filename, access="sequential")
    image.write_to_file(output_filename)


img1 = np.random.randint(0, 255, (300, 300, 4), dtype=np.uint8)
save_pyr(img1, "img_shared_filename.tiff")
save_tif("img_shared_filename.tiff", "img_blended_1.tiff")


img1 = np.random.randint(0, 255, (300, 300, 4), dtype=np.uint8)
save_pyr(img1, "img_shared_filename.tiff")
save_tif("img_shared_filename.tiff", "img_blended_1.tiff")
```

Fails for me with:

```
$ ./ido.py 
Traceback (most recent call last):
  File "/home/john/try/./ido.py", line 24, in <module>
    save_tif("img_shared_filename.tiff", "img_blended_1.tiff")
  File "/home/john/try/./ido.py", line 14, in save_tif
    image.write_to_file(output_filename)
  File "/home/john/.local/lib/python3.11/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/lib/python3.11/site-packages/pyvips/voperation.py", line 305, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignSaveTiffFile
  source input: Using code not yet in table
source input: Using code not yet in table
source input: Using code not yet in table
source input: Using code not yet in table
```

But I'm not sure why. I guess I'll need to dig a bit, perhaps later next week.
