### ISSUE TITLE
pyvips.error.Error: no such operation smartcrop

### ISSUE THREAD

**Issue by jflat06** [libvips/pyvips#62]
Hi,
I am trying to use the smartcrop feature, and it looks like it isn't picking up the binding. 

```
import pyvips
img = pyvips.Image.new_from_file('inv/1/0001_0001.tif', access='sequential')
img.smartcrop(100,100,interesting='attention')
```
This results in the following stack trace:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    img.smartcrop(100,100,interesting='attention')
  File "/home/jflat06/.local/lib/python2.7/site-packages/pyvips/vimage.py", line 799, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/home/jflat06/.local/lib/python2.7/site-packages/pyvips/voperation.py", line 132, in call
    op = Operation.new_from_name(operation_name)
  File "/home/jflat06/.local/lib/python2.7/site-packages/pyvips/voperation.py", line 60, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation smartcrop
  VipsOperation: class "smartcrop" not found
```

This is using version 2.1.3 on Ubuntu 18.04:
```
$ pip show pyvips
Name: pyvips
Version: 2.1.3
Summary: binding for the libvips image processing library, ABI mode
Home-page: https://github.com/jcupitt/pyvips
Author: ---
Author-email: ---
License: MIT
Location: /home/user/.local/lib/python2.7/site-packages
Requires: cffi
```

**Comment by jflat06** [comment]
Ah... the library version available in ubuntu isn't recent enough. I built it from source, and now I have smartcrop available. 

However, the following now crashes for me with a segfault:

```
In [1]: import pyvips

In [2]: img = pyvips.Image.new_from_file('inv/1/0001_0001.tif', access='sequential')

In [3]: outimg = img.smartcrop(100,100,interesting='attention')

In [4]: outimg.write_to_file('test.png')
Segmentation fault (core dumped)
```

**Comment by jflat06** [comment]
It's worth noting that the command line version does work for me:

vipsthumbnail -s 100x100 --smartcrop attention inv/1/0001_0001.tif

**Comment by jcupitt** [comment]
Hello @jflat06,

Take off the `access=` and it should work. Sequential mode is for streaming -- where you're just doing operations which do simple top-to-bottom processing -- and smartcrop involves a series of searches.

**Comment by jflat06** [comment]
Thanks, that appears to have worked.
