### ISSUE TITLE
UnicodeDecodeError on error.py:_to_string

### ISSUE THREAD

**Issue by vaurelios** [libvips/pyvips#80]
Python: 3.7
pyvips: 2.1.5
OS: Windows 7 x64 (PT-BR)

Reproducible code:
```
import pyvips

img = pyvips.Image.text("test")
img.write_to_file("a.png")
```
Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\pyvips\vimage.py", line 500,
 in write_to_file
    string_options=options, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\pyvips\voperation.py", line
189, in call
    raise Error('unable to call {0}'.format(operation_name))
  File "C:\Program Files\Python37\lib\site-packages\pyvips\error.py", line 67, i
n __init__
    detail = _to_string(vips_lib.vips_error_buffer())
  File "C:\Program Files\Python37\lib\site-packages\pyvips\error.py", line 41, i
n _to_string
    x = x.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 86: invalid
 continuation byte
```
Changing line 41 to `x = x.decode('cp1254')` decodes without error but of course, this isn't the right solution.

**Comment by int-ua** [comment]
This issue seems to affect Windows users of pyvips, I've seen two people now complaining about it when trying to use https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tools/gfx_tools/compose.py

**Comment by rafaelkb** [comment]
Python 3.9.1
pip 20.3.3

LCID             Name             DisplayName
----             ----             -----------
1046             pt-BR            Português (Brasil)

**Comment by int-ua** [comment]
Looks similar to https://github.com/elyase/geotext/issues/3

**Comment by int-ua** [comment]
Is it https://github.com/libvips/libvips/issues/1743 ?
