### ISSUE TITLE
pyvips in Docker environment

### ISSUE THREAD

**Issue by EunsungKoh** [libvips/pyvips#83]
Hi there,
This issue is related with  #76 .

I'll borrow my previous comments in #76 in below.

-------------------------------------------------------------------

Hello @jcupitt , 
I'm using docker environment and python 3.7.
I think I'm suffering similar issues.
Can I get a any hint for this issue?

```
~$ docker exec -it 2b14 /bin/bash
root@2b147d09f5d5:/conduit# pip3.7 install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.0.1)
root@2b147d09f5d5:/conduit# pip3.7 install pyvips
Requirement already satisfied: pyvips in /usr/local/lib/python3.7/site-packages (2.1.5)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/site-packages (from pyvips) (1.11.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.0.0->pyvips) (2.19)
root@2b147d09f5d5:/conduit#  python3.7
Python 3.7.2 (default, Jan 23 2019, 02:31:57) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 69, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
```

------------------------------------------------------------------
> https://github.com/libvips/pyvips/issues/76#issuecomment-459685994
> @jcupitt commented
> Have you installed the libvips library? It looks like it can't be found by pyvips.
> If you can't fix it, please open a new issue and share your Dockerfile.

-------------------------------------------------------------------

I think I don't have libvips in docker environment as you told.
Though I want to download a libvips in docker env, I can not find easy and precise way.
I downloaded libvips in my local linux(ubuntu) env with just command ```apt install libvips-tools```.

So, Can you please let me know the precise way to download libvips library in docker environment? 

By the way, Its my Dockerfile
```
 FROM python:3
 ENV PYTHONUNBUFFERED 1
 RUN mkdir /backend
 WORKDIR /backend
 ADD requirements.txt /backend/
 RUN pip install -r requirements.txt
 ADD . /backend/
 EXPOSE 8000
```
and requirements.txt
```
Django==1.9.6
django-extensions==1.6.7
djangorestframework==3.3.3
PyJWT==1.4.0
six==1.10.0
django-cors-headers
psycopg2
```

Also using docker-compose
```
  backend:
    build: .
    volumes:
      - ./:/conduit 
    working_dir: /conduit/
    command: sh entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - db
```
and entrypoint.sh
```
pip install -r requirements.txt
python manage.py migrate
python manage.py runserver 0.0.0.0:8000
```

Sorry for my broken english.

Sincerely,
Eunsung Sam Koh

**Comment by jcupitt** [comment]
You just need to update and upgrade in your dockerfile. Perhaps:

```
 FROM python:3
 ENV PYTHONUNBUFFERED 1
 RUN apt -y update && apt -y upgrade && apt -y install libvips
 RUN mkdir /backend
```

`python:3` is based on Debian stretch and the libvips package there is huge. It seems to depend on everything. If you build libvips yourself, you can make it much smaller.

**Comment by EunsungKoh** [comment]
Unfortunately, update and upgrade of my dockerfile didn't make any changes.

*Dockerfile*
```
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN apt -y update && apt -y upgrade && apt -y install libvips
RUN mkdir /backend
WORKDIR /backend
ADD requirements.txt /backend/
RUN pip install -r requirements.txt
ADD . /backend/
EXPOSE 8000
```

*bash*
```bash
$ docker exec -it f785 /bin/bash

root@f785f6ecfbba:/conduit# pip install pyvips
Collecting pyvips
  Downloading https://files.pythonhosted.org/packages/39/1e/b1df477d78bba37d3b9f83258e9a44bb505355e2e56a82e8398bfe699096/pyvips-2.1.5.tar.gz
Collecting cffi>=1.0.0 (from pyvips)
  Downloading https://files.pythonhosted.org/packages/51/7b/d1014289d0578c3522b2798b9cb87c65e5b36798bd3ae68a75fa1fe09e78/cffi-1.11.5-cp37-cp37m-manylinux1_x86_64.whl (421kB)
    100% |████████████████████████████████| 430kB 1.9MB/s 
Collecting pycparser (from cffi>=1.0.0->pyvips)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 1.4MB/s 
Building wheels for collected packages: pyvips, pycparser
  Building wheel for pyvips (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/f2/6f/17/d9ffd381fb595e7ad94028093c0ff706da9c8a8608626e1b20
  Building wheel for pycparser (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pyvips pycparser
Installing collected packages: pycparser, cffi, pyvips
Successfully installed cffi-1.11.5 pycparser-2.19 pyvips-2.1.5

root@f785f6ecfbba:/conduit# python3 pyv.py 
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyv.py", line 3, in <module>
    import pyvips
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 69, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
```
-------------------------------------

I'm trying to make an application which makes svs files into dzi files and can show dzi format images through OpenSeaDragon for pilot projects. 
As this project is not for production which focus on practice and implementation, I'm actually not concern about optimization that much.
However, if making own libvips affects whether it works or not, I'll make it. 

Thanks for helping me.

**Comment by kuhnchris** [comment]
Hmmm, I tried aswell with the Dockerfile above, it works here tho.

```/home/kuhnchris# docker run -it xx bash
root@eb475ba55f44:/# pip install pyvips
Collecting pyvips
  Downloading https://files.pythonhosted.org/packages/39/1e/b1df477d78bba37d3b9f83258e9a44bb505355e2e56a82e8398bfe699096/pyvips-2.1.5.tar.gz
Collecting cffi>=1.0.0 (from pyvips)
  Downloading https://files.pythonhosted.org/packages/51/7b/d1014289d0578c3522b2798b9cb87c65e5b36798bd3ae68a75fa1fe09e78/cffi-1.11.5-cp37-cp37m-manylinux1_x86_64.whl (421kB)
    100% |________________________________| 430kB 5.4MB/s
Collecting pycparser (from cffi>=1.0.0->pyvips)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |________________________________| 163kB 3.5MB/s
Building wheels for collected packages: pyvips, pycparser
  Building wheel for pyvips (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/f2/6f/17/d9ffd381fb595e7ad94028093c0ff706da9c8a8608626e1b20
  Building wheel for pycparser (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pyvips pycparser
Installing collected packages: pycparser, cffi, pyvips
Successfully installed cffi-1.11.5 pycparser-2.19 pyvips-2.1.5
root@eb475ba55f44:/# python3
Python 3.7.2 (default, Feb  6 2019, 12:04:03)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>>
```

Did you delete the container and rebuild it with docker build? 
Also, do me a favor and check if the files exist in the container:
```
/usr/lib/x86_64-linux-gnu/libvips-cpp.so.42.6.5
/usr/lib/x86_64-linux-gnu/libvips-cpp.so.42
/usr/lib/x86_64-linux-gnu/libvips.so.42
/usr/lib/x86_64-linux-gnu/libvipsCC.so.42.6.5
/usr/lib/x86_64-linux-gnu/libvips.so.42.6.5
```

Thanks!

**Comment by jcupitt** [comment]
Yes, works for me too. I made you a complete Dockerfile:

https://github.com/jcupitt/docker-builds/tree/master/pyvips-python3

I see:

```
$ docker build -t pyvips-python3 .
Sending build context to Docker daemon  15.87kB
...
Successfully built pyvips pycparser
Installing collected packages: pycparser, cffi, pyvips
Successfully installed cffi-1.11.5 pycparser-2.19 pyvips-2.1.5
Removing intermediate container 10237d85e203
 ---> 39e76254370f
Successfully built 39e76254370f
Successfully tagged pyvips-python3:latest
```

Then:

```
$ docker run --rm -it pyvips-python3
Python 3.7.2 (default, Feb  6 2019, 12:04:03) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> 
```

**Comment by EunsungKoh** [comment]
Thanks @jcupitt @kuhnchris !

Following yours replies, I found my container and image goes something wrong.
There was no libvips files on my ```/usr/lib/x86_64-linux-gnu/``` directory and 
 [pyvips-python3/](https://github.com/jcupitt/docker-builds/tree/master/pyvips-python3) dockerfile was perfectly worked with my machine. 
It's dockerfile was exactly same with mine though.

So, I deleted all my images and did docker-compose up again.
Now It works like charm :grin: 

Thanks again!

**Comment by EunsungKoh** [comment]
I think I can use pyvips now on, but I saw small issue is still left.
```bash
root@1da62dffdd8f:/conduit# python3 pyv.py 
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fda776c4518>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fda776bb390>
DEBUG:pyvips:Inited libvips

root@1da62dffdd8f:/conduit# python3
Python 3.7.2 (default, Feb  6 2019, 12:04:03) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> 
```
As you can see, If I run the ```pyv.py``` It says ``` No module named '_libvips'``` .
However, if I import pyvips manually after run python3, python3 doesn't make any problem log.

Though I can use a pyvips now, as I found small issue I made this comment.

Thanks!

**Comment by jcupitt** [comment]
Ooops, you're right, you need to install `libvips-dev` so that cffi can build the native interface. I updated that dockerfile and I now see:

```
$ docker run --rm -it -v $PWD:/data pyvips-python3 
Python 3.7.2 (default, Feb  6 2019, 12:04:03) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level = logging.DEBUG)
>>> import pyvips
DEBUG:pyvips:Loaded binary module _libvips
DEBUG:pyvips:Inited libvips
>>> 
```

**Comment by EunsungKoh** [comment]
Finally It works!

```bash
root@837287600fd5:/conduit# python3
Python 3.7.2 (default, Feb  6 2019, 12:04:03) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level = logging.DEBUG)
>>> import pyvips
DEBUG:pyvips:Loaded binary module _libvips
DEBUG:pyvips:Inited libvips
>>> 
```

THANKS @jcupitt :+1:
