### ISSUE TITLE
Pyvips crashes when rendering an image of an ampersand

### ISSUE THREAD

**Issue by MisterMorden** [libvips/pyvips#93]
When I ask pyvips to render text containing an ampersand as an image, it crashes.  For instance, the following code crashes:

```python
import pyvips
import numpy as np
from PIL import Image

image = pyvips.Image.text('&', dpi=300, font='')
mem_image = image.write_to_memory()
numpy_image = np.fromstring(mem_image, dtype=np.uint8).reshape(image.height, image.width)
pil_image = Image.fromarray(numpy_image, mode='L')
pil_image.save('foo.jpg')
```

...with the following error message:

```
Traceback (most recent call last):
  File "D:/Res/pyvips testing/pyvips crash.py", line 5, in <module>
    image = pyvips.Image.text('&', dpi=300, font='')
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\Lib\site-packages\pyvips\vimage.py", line 128, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\Lib\site-packages\pyvips\voperation.py", line 189, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call text
  text: invalid markup in text
```

While the following code executes correctly:

```python
import pyvips
import numpy as np
from PIL import Image

image = pyvips.Image.text('foo', dpi=300, font='')
mem_image = image.write_to_memory()
numpy_image = np.fromstring(mem_image, dtype=np.uint8).reshape(image.height, image.width)
pil_image = Image.fromarray(numpy_image, mode='L')
pil_image.save('foo.jpg')
```

And yields the following image:

![foo](https://user-images.githubusercontent.com/29239528/56005292-7fbc5c00-5c84-11e9-89ba-c8f069368daa.jpg)

**Comment by jcupitt** [comment]
Hello @MisterMorden,

It's not really a crash, you just have invalid markup in your text. The `text` operator takes a Pango Markup string:

https://libvips.github.io/libvips/API/current/libvips-create.html#vips-text

Pango markup is described here:

https://developer.gnome.org/pango/stable/PangoMarkupFormat.html

So to draw an ampersand you use:

```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.text("a&amp;b", dpi=300)
>>> x.write_to_file("x.png")
```

To make:

![x](https://user-images.githubusercontent.com/580843/56022524-cef5a180-5d03-11e9-8cb1-68540f7676dd.png)

**Comment by MisterMorden** [comment]
Thank you!
